#spring.application.name=driveguard
#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/driveguard?createDatabaseIfNotExist=true
#    username: ayesh
#    password: 123@ayesh
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: false

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/driveguard?createDatabaseIfNotExist=true
    username: ayesh
    password: 123@ayesh
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



